
from gensim import corpora, models, similarities
import jieba
import pandas as pd

# data loading

syntetic_texts = ['Masivul Buila-Vânturariţa este situat în partea central-nordică a Judeţului Vâlcea şi face parte din Munţii Căpăţânii. Masivul iese în evidenţă faţă de lanţul principal al acestora, atât prin dispunere cât şi prin constituţie şi relief. Creasta principală a Munţilor Căpăţânii, constituită preponderent din şisturi cristaline are o dispunere est-vest, cu creste secundare înspre nord şi sud. Excepţie fac două masive calcaroase, ale căror creste principale sunt dispuse pe direcţia SV-NE: Masivul Târnovu în nord-vest şi Masivul Buila-Vânturariţa în sud-est. Parcul Naţional Buila-Vânturariţa are 6 puncte de intrare: 3 în Comuna Costeşti – unul pe Valea Bistriţa şi două pe Valea Costeşti: Bistriţa, Pietreni-Prislop şi Pietreni-Valea Morii; 1 în Comuna Bărbăteşti pe Valea Otăsăului; 1 în Satul Cheia pe Valea Cheia; 1 în Oraşul Băile Olăneşti pe Valea Olăneşti. Accesul se poate face fie pe drumul naţional 67 Rm. Vâlcea-Târgu Jiu, fie pe drumul judeţean Rm. Vâlcea-Băile Olăneşti. Întreaga reţea hidrografică a Masivului Buila-Vânturariţa este tributară Râului Olt, prin afluenţi direcţi sau indirecţi de dreapta ai acestuia, cu o direcţie de curs, în linii mari de la nord la sud. Principalele râuri care curg în masiv sunt, de la sud-vest la nord-est: Bistriţa, Costeşti, Otăsău, Cheia, Olăneşti. La capitolul lacuri şi acumulări de apă masivul este sărac, fiind prezente doar câteva mici lacuri: cele antropice din Pietreni, generate de alunecarea stratelor pe care s-a depus halda de steril de la cariera Bistriţa, două mici iazuri (topliţe) pe Cheile Bistriţei şi câteva mici tăuri în dolinele din zona Muntelui Piatra, care în verile secetoase seacă aproape complet. În schimb apele subterane au fost foarte active, generând numeroase fenomene endocarstice, reprezentate prin peste 100 peşteri, la care se adaugă numeroase fenomene exocarstice. Sunt prezente numeroase surse de apă de tipul izbucurilor, dintre care cel al Izvorului Frumos de lânga Schitul Pahomie este cel mai important. Altele mai mici se găsesc la nord de Curmătura Builei (La Troiţă), Poiana Scărişoara, Poiana Pătrunsa, Bistriţa.Taxă de intrare: 5 lei/adult (valabilitate 7 zile)',
         'Aflată la 1600 m altitudine, în imediata apropiere a Hotelului Peștera, este unul din cele mai importante obiective turistice ale Bucegilor. Adâncimea porțiunii accesibile este de 400m. Deschiderea la intrare 15m. Peștera este în întregime electrificată iar accesul turiștilor se face pe scări de lemn',
         'Istoria orașului Petroșani începe undeva pe la 1640, unde douăzeci de iobagi din Petros, pot fi considerați primii locuitori care apar în documentele vremii, ai acestui ținut. În 1840 încep primele exploatări în suprafață ale zăcămintelor de cărbuni simultan la Vulcan, Petroșani și Petrila iar în 1845, apar migrații masive ce vizează mineri germani în mare parte din Bucovina, dar și din restul Transilvaniei.Punct de plecare spre Vârful Parâng şi staţiunea montană de schi',
         'Biserica cu picturi murale a Mănăstirii Voroneţ (Patrimoniul UNESCO) zzzz,"Voroneţ, SV","Ea constituie una dintre cele mai valoroase ctitorii ale lui Ștefan cel Mare. Biserica a fost ridicată în anul 1488 în numai patru luni și jumătate ceea ce constituie un record pentru acea vreme.Viata monahală s-a întrerupt in anul 1785 dupa anexarea Bucovinei la Imperiul Habsburgic și s-a reluat în anul 1991.',
         'Vârful Moldoveanu,"Bâlea Lac, AG",Cel mai înalt vârf din România (2544 m). Pentru cei pasionaţi de trasee montane. În apropiere este Refugiul Vistea şi Iezerul Triunghiular.',
         'Al doilea cel mai înalt vârf muntos din România (2535 m). Pentru cei pasionaţi de trasee montane. În apropiere este Lacul Călţun.' ,
         'Vila Florica Brătianu,"Ştefăneşti, AG"," Conacul familiei  Brătianu, numit ca şi satul în care se care se află, Florica, în amintirea primei fiice a lui I.C. Brătianu – este unul din cele mai frumoase domenii boiereşti din România, păstrat foarte bine până în zilele noastre ( cu exceptia obiectelor, mobilelor şi a cărtilor din interior, risipite aiurea în anii regimului comunist ). Este conacul în care s-a născut şi a trăit cea mai importantă familie de oameni politici români, o adevarată dinastie civilă care a dat țării nu mai putin de trei prim-miniştri, dintre care primii doi – Ion si Ionel Brătianu – au avut un rol covârşitor în realizarea României moderne ( de numele primului legându-se razboiul Independenței, cel de-al doilea realizând – tot în urma unui război – Unirea din 1918 şi reformele ce au stat la baza democrației interbelice ).',
         'Situl arheologic Basarabi-Murfatlar se află la o distanță de 15 km de litoralul Mării Negre, pe malul drept a ceea ce a fost Valea Carasu, acum Canalul Dunăre-Marea Neagră. Este alcătuit din camere și galerii, fiind săpat într-un deal de cretă situat în apropierea carierei de extragere a cretei din Basarabi. A fost descoperit pe 11 iunie 1957, în urma unor lucrări de extindere a zonelor de exploatare a cretei. Acest complex, a adăpostit, în opinia cercetătorilor, prima biserică și primele chilii ale unei mănăstiri de pe teritoriul României."'
         ]
keyword ='Vreau sa merg la litoralul Mării Negre si as vrea sa vizitez Canalul Dunăre-Marea Neagră '
texts = [jieba.lcut(text) for text in syntetic_texts]
dictionary = corpora.Dictionary(texts)
feature_cnt = len(dictionary.token2id)
corpus = [dictionary.doc2bow(text) for text in texts]
tfidf = models.TfidfModel(corpus)
kw_vector = dictionary.doc2bow(jieba.lcut(keyword))
index = similarities.SparseMatrixSimilarity(tfidf[corpus], num_features = feature_cnt)
sim = index[tfidf[kw_vector]]
for i in range(len(sim)):
 print('keyword is similar to text%d: %.2f' % (i + 1, sim[i]))